### ISSUE TITLE
Revisión Mercado Liebre

### ISSUE THREAD

**Issue by lucianafigueroa** [Florsecco/mercado-liebre#1]
- [ ] 1- Cumple
- [ ] 2- a) Cumple b) Falta el margen inferior de separación de 10 píxeles:

```
.clase-footer i {
    color: #1259c3;
    font-size: 2em;
    margin-bottom: 5px;
    margin-top: 5px;
}
```
- [ ] 3- Cumple
- [ ] 4- Cumple
- [ ] 5- Cumple
- [ ] 6- Cumple
- [ ] 7- Cumple
- [ ] 8- Cumple
- [ ] 9- Me gusta la página, desde el posicionamiento de los elementos hasta las distintas transiciones, como así también los tamaños en general ya que hace que la página sea estética. Destaco además el tamaño del logo ya que se adecua a los distintos tamaños de pantalla y esto hace que sea vea mejor visualmente.
- [ ] 10- Creo que lo único que puede mejorar (detalles mínimos) es que el footer sea un poco más alto e incorporar títulos en creá tu cuenta y en login para la accesibilidad web. Por último, me gustaría que el botón enviar en creá tu cuenta esté del lado izquierdo del borrar. Fuera de esto, la página está perfecta.

Títulos (en donde falte, ya que no faltan en todos) arriba de los inputs de estas imágenes:
Por ejemplo, colocar un titulo en esta imagen que indique el inicio de sesión.
![image](https://github.com/Florsecco/mercado-liebre/assets/146852103/69ef9584-a011-4c92-b7cc-4a5c17494bcc)

Por ejemplo, colocar un titulo en esta imagen que indique el registro de usuario.
![image](https://github.com/Florsecco/mercado-liebre/assets/146852103/65a4f91c-0947-45a7-8ab4-30b6853163d5)

Botones a cambiar de lugar:
![image](https://github.com/Florsecco/mercado-liebre/assets/146852103/0138825d-c43e-4e77-89b3-9b728c92b066)

**Comment by Florsecco** [comment]
Muchas gracias por las observaciones Lu, ya corregi el margen y tome las recomendaciones!
