### ISSUE TITLE
Revision Mercado Liebre #2

### ISSUE THREAD

**Issue by decimechochi** [Florsecco/mercado-liebre#2]
2 - al margen inferior derecho le faltan los 10 px.
 Para mejorar: solo falto que la animacion del camion de envios gire cuando se toque la tarjeta y no solo el camion. 

El trabajo esta impecable!, prolijo y tal como se pide., 
Felicidades flor!

**Comment by Florsecco** [comment]
Muchas gracias por las observaciones Ro, ya corregi el margen.
